/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Allow the service worker to skip waiting when an update is available and the user accepts it
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Handle push events
self.addEventListener('push', (event) => {
  let data: { title?: string; body?: string } = {};
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch {
      data = { body: event.data.text() };
    }
  }

  // Validate and sanitise payload fields to prevent spoofed notifications
  const title =
    typeof data.title === 'string' && data.title.length > 0 && data.title.length <= 100
      ? data.title
      : 'SipWise';
  const body =
    typeof data.body === 'string' && data.body.length > 0 && data.body.length <= 250
      ? data.body
      : 'Time to check your BAC!';

  const options = {
    body,
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    vibrate: [100, 50, 100],
    data: { url: self.registration.scope },
  } as NotificationOptions;

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});


// Handle notification click events
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Focus or open the application
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      const scope = self.registration.scope;
      
      // Look for an open app window matching our scope
      for (const client of clientList) {
        if (client.url.startsWith(scope) && 'focus' in client) {
          return client.focus();
        }
      }
      
      // If no open window, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(scope);
      }
    })
  );
});

// Handle background sync events for offline-first drink logging & cloud sync
self.addEventListener('sync', (event: Event & { tag?: string; waitUntil?: (p: Promise<unknown>) => void }) => {
  if (event.tag === 'sync-sipwise-data') {
    event.waitUntil?.(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        for (const client of clients) {
          client.postMessage({ type: 'BACKGROUND_SYNC_TRIGGERED' });
        }
      })
    );
  }
});
